### ISSUE TITLE
Should we retain v1 spec on the site?

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#105]
If people are still working with earlier versions of the API/tracers, there will be no way to access the specs once we commit v2 spec.

@bensigelman

**Comment by bensigelman** [comment]
It was always an "RC" because we knew there were some concerns with it... In the long run we should absolutely document and advertise earlier versions of the spec, but I'm not so sure in the short run.

That said, if someone else is willing to do the work (and the opentracing.io site makes it clear which version is current, etc), I wouldn't object to this. Just seems like it might be a lot of effort to do well.

**Comment by yurishkuro** [comment]
I've been thinking of a simple way to do that with Jekyll, but haven't quite nailed it. We need:
 * [ ] individual specs documents to be under `/vN.M/` path instead of root
 * [ ] links from specs to specs should be relative
 * [ ] the left-side menu must preserve the path prefix
 * [ ] the home page links should point to `latest` (can be just a copy of the latest `vN.M` dir, as a build step)
 * [ ] perhaps the navigation should be reworked to separate version-independent pages (like Contributors) from the actual specs pages
