### ISSUE TITLE
RFC: Include sampling in the spec

### ISSUE THREAD

**Issue by dominikh** [opentracing/opentracing.io#109]
Right now, the spec intentionally doesn't mention sampling. And indeed, some parts of sampling (client-side vs server-side, ...) depend on the specific implementation. There are, however, two parts to sampling that could, and most likely should, be covered in the spec:
1. Baggage propagation shouldn't be affected by sampling.
2. We do have a standard tag for the sampling priority. This leads me to believe that we should document the tag in the spec, and specify that there needs to be a way to force sampling of a request.

I'm somewhat ambivalent about point 2 and will easily be convinced that this is too implementation-specific. I do feel strongly about point 1.

/cc @bensigelman @adriancole @yurishkuro

**Comment by bg451** [comment]
@dominikh  I'm curious to hear your reasoning for point 1 and get a better understanding of it. To be upfront I don't have an opinion on this so bear with me for a second.

If I have some tracing implementation that only supports upfront sampling, such that only the root span gets to make that decision, one thing I might want to do is use a Noop span implementation to reduce the overhead of something that isn't being recorded anyway. Adding baggage doesn't do anything and as a result baggage is essentially disabled. Would this use case be in violation of point 1 or is this irrelevant since children spans have no say in sampling? Maybe I'm thinking too specifically?

**Comment by dominikh** [comment]
@bg451 The way I understood @bensigelman on Gitter, baggage may be used to transmit data that is useful for things like resource usage accounting or authentication information. From that follows that baggage shouldn't be affected by the sampling of a trace.

**Comment by bensigelman** [comment]
@dominikh I appreciate (and even agree with) your core point: that baggage propagation isn't useful unless it's always-on. That said, OpenTracing is only designed to work properly when the *entire* distributed system uses Tracer implementations from the same vendor (whether that be Zipkin, Appdash, whatever); as such, why not leave this matter to the tracing implementations?

I.e., if someone wants to create a MinimumOverheadTracer that drops baggage some of the time, they just need to be sure to advertise that fact... developers who *use* OpenTracing can adopt or not-adopt MinimumOverheadTracer as they choose.

My thinking here is just that some people will never use baggage (which is fine), and they may want to adopt Tracer impls that are more efficient because they don't support it in some/all cases.

I recognize that I'm basically arguing against true interop here... I think that's because I've considered Baggage to be an experimental feature. I would be less willing to forgive/accept a Tracer implementation that didn't support `Span.SetTag`, for instance.

**Comment by dominikh** [comment]
@bensigelman Come to think of it, my first point isn't really about sampling, but about the fact that baggage itself isn't defined very well. Including myself, I know of two people so far who made the mistake of applying sampling to baggage, because baggage sounded like a variation of tags that just avoids extra roundtrips to get to the data.

It isn't made clear that baggage is really about context propagation and that baggage and tracing are really two different concepts stuffed into the same spec.

However, to fully explain baggage, sampling needs to be at least mentioned.

My second point, however, truly is about sampling. We have a standard tags whose semantics aren't well defined because things like forced sampling aren't covered in the spec. IMO, tags should have a consistent meaning across implementations as much as possible.

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/11.
