### ISSUE TITLE
Not clear how to submit PRs

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#128]
Aside from changing the actual source file, does a PR need to include the files that get modified under `documentation/` folder? I haven't even changed anything in the documentation, only the homepage. Please clarify in the README.

@reimertz

**Comment by bensigelman** [comment]
@yurishkuro agree this should be clarified... I got by with a one-time `npm install` followed by `npm run production` prior to submit.

There are a bunch of genfiles which change every time and which should probably be part of a TravisCI step. @reimertz would be better able to make specific suggestions.

**Comment by yurishkuro** [comment]
Or even better not to have those files changes. As far as I can tell, the change is two-fold, some timestamp is included in JS inside HTML, not sure why, and a couple of js files get a filename based on unix timestamp (things like webpack usually just hash the file content for cache busting, which results in stable file names).

Overall, I am not sure why we need Node to be involved in a jekyll-based site, but then again it was clearly a lot of work to renovate the website that I personally didn't have to do, so I won't complain :-).

**Comment by bensigelman** [comment]
@yurishkuro I think the TL;DR is `gitbook` which has some fancy client-side search features, etc. But I don't actually know (or, frankly, care) either.

Usually when timestamps are involved, it's a way of guaranteeing that browser caches get cleared "no matter what". Not sure if that's the case here.

**Comment by reimertz** [comment]
@yurishkuro I agree with you, the process right is too complex right now and the reason is, as @bensigelman mentioned, because we use gitbook for the documentation part of the page.  I think this flow ended up a bit backwards and needs to be solved.

I think the best solution for this is to add /documentation in the .gitignore and instead run build steps with travis once we get a push to master.

We can then add a badge to in the readme to will show if the latest commit on master is broken or not. 

To clarify how a PR should be done, I could create CONTRIBUTE.md with steps necessary to submit a PR.
