### ISSUE TITLE
automatic travis build take 2

### ISSUE THREAD

**Issue by reimertz** [opentracing/opentracing.io#142]
Sadly, due to the differences between how `*.github.io`  and `*.github.io/project` are being built and served by github, our current repo isn't compatible with the automatic travis build that I implemented. 

I propose that we rename this repo to `opentracing.io`, which will give os the ability to select which branch we want to use as our source for the static content. Github will also do a 301 from opentracing.github.io -> opentracing.io so there won't be any noticeable side-effects. 

This would remove the need of running `npm run production` before each individual commit to master. That means no more changes in `/documentation` which is causing each commit to be huge at the moment.

Also, we'll be able to see if a PR is breaking the build or not which is nice. 😄 

I would say this is a win-win.

**Comment by bensigelman** [comment]
... related to this, I'm going to propose (separately, and not today since I'm busy with something else) that we create something like `github.com/opentracing/core` which would provide a home for structured data that addresses https://github.com/opentracing/opentracing.github.io/issues/76 as well as future issues around core OpenTracing semantics. I guess we'd have to manually migrate existing open issues about OpenTracing semantics from the docs repo, but that would be a one-time thing.

**Comment by reimertz** [comment]
Okay, since no one had any opinions/remarks, I would say we should go with this for now. It would remove a lot of the hassles we currently have. :)

**Comment by bensigelman** [comment]
SGTM

**Comment by reimertz** [comment]
Can you then rename the repo so I can initiate the switch?

**Comment by bensigelman** [comment]
@reimertz done :)

I am going to do some hard-refreshes over the next 5m to make sure there are no problems, but seems good so far. At the first sign of trouble I will revert the rename, though. I think the `301` redirects are going to pave over any difficulties.

**Comment by reimertz** [comment]
I think we can close this ticket now, because everything seems to work flawlessly.
