### ISSUE TITLE
Semantic Conventions has broken link to the spec

### ISSUE THREAD

**Issue by jpkrohling** [opentracing/opentracing.io#349]
The first link on the contents of the [Semantic Conventions page](https://opentracing.io/specification/conventions/) has a broken link to the specification. It currently links to https://opentracing.io/specification/conventions/specification.md , but should be https://opentracing.io/specification/

![image](https://user-images.githubusercontent.com/13387/47213140-78358d80-d39a-11e8-93f5-e4c053a92fa0.png)

**Comment by austinlparker** [comment]
Yeah, that's a tricky one to fix because all of the files in the specification section are actually coming in via a submodule of the Specification repo itself. Since the files are the ones from the spec repo, all of the links are relative to that repository rather than the website. I'm not sure the best way to fix it to be honest; We could scrap the submodule and just manually update the website spec when the real spec changes, or we could try to come up with something clever.

**Comment by jpkrohling** [comment]
> Yeah, that's a tricky one to fix

That's why I didn't open a PR right away :smile:

**Comment by jan25** [comment]
There are more links in opentracing.io with similar problem that directly point to `.md` files in specification repo. Not sure if Hugo has some feature to handle such scenarios, where we specify how to handle a specific route for example `<a>` tag with `specificiation.md` would instead route to to `/specification`.
