### ISSUE TITLE
Could we standardize aspects of the sampling mechanism?

### ISSUE THREAD

**Issue by lookfwd** [opentracing/opentracing.io#94]
I was wondering if it would be possible to put a function or so to these APIs to allow a degree of standardization of the sampling mechanism. Here are some thoughts. Motivation:

> I'm the website owner and I have a session id and a user id for every user who is logged in. Slow operations appear on the `createNewWhatever()` function in about 1:1000 users I have tracing sampling ratio to 1:100 so I'm getting about 1% of traces/spans that capture slowness. Let's assume that I find out that user with id 123 has slow e.g. page loads. I suspect that that's because he's doing a `refresh()` in another tab or something. The problem is that given that I have 100 Million (whatever) users, it's quite unlikely I also have trace for that user's `refresh()` method."

I believe we can enhance slightly the API to allow application developers to incorporate application knowledge to the sampling mechanism. It might be as simple as an optional `sampling_id` on one of the `start_span()` functions. This could be a user-controlled potentially uniformly distributed number ranging from 0 - 100k. It could default to a random number. This number affects `traceid` (or other propagated id's) generation in order to allow implementations to universally capture complete information for trace subsets across different microservices without adding any performance overhead.

For a given `sampling_id` number, tracing will consistently be enabled or disabled across multiple processes/servers. The property of being enabled or disabled should remain stable unless implementation's configuration changes. Different implementations are allowed to use whatever rule they want to identify if a given `sampling_id` is enabled for tracing or not.

What do you think?

**Comment by yurishkuro** [comment]
Hi Dimitros,

The main reason sampling is not in OpenTracing API is because not all tracing systems are actually doing the traditional pre-trace sampling, because it leads to exactly the problems you describe.  However, given that many tracing implementations actually do use sampling, there is a standard tag `sampling.priority` that instrumentation code can set on a span to hint the tracing system that a given trace is "interesting" (or not, if set to 0). The API does not dictate how the tracing system is expected to treat that tag, however, it's up to the implementation.

If your application has a prior knowledge that a certain request is going to be "interesting", then this mechanism can help to capture more of the anomalous traces. But the main problem is that it's usually impossible to say upfront if the trace is going to be interesting, which is why some more advanced tracing systems are not using pre-trace sampling.

**Comment by lookfwd** [comment]
Nice! Those are relatively new parts of the spec. Might be just a few constants but I haven't added them yet in C++.

So the way one does it is this. If ones sees that the user with `user_id`==target, they set the `sampling.priority` to `1` which might make the system trace everything for that user. Alternatively one could define a "random" slice of the users to be traced by setting `sampling.priority = 1` for e.g. `user_id % 100 == 1` effectively suggesting an application-side 1:100 ratio. The latter is a bit too aggressive though since as implementer I'm left with the options either to ignore the `priority` or implicitly have effective sampling 1:100 or have a complex implementation that selectively ignores `sampling.priority` to ensure that 1:10000 is respected.

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/11
